### Send SMS
POST http://localhost:3000/send-sms
Content-Type: application/json

{
  "sender": "HealthLine",
  "message": "Hello, this is a test message 4 !",
  "recipients": ["233553266543", "233200213177"]
} 
